server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:minalz/minalz-cloud-config-2020.git #GitHub上面的git仓库名字
        ####搜索目录
          search-paths:
            - minalz-cloud-config-2020
      ####读取分支
      label: master
#rabbitmq相关配置
  rabbitmq:
    host: 47.96.73.9
    port: 5672
    username: zhouwei
    password: zhouwei123

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


